### ISSUE TITLE
`HTTPEvents` filtering actual response headers

### ISSUE THREAD

**Issue by losadaem** [logtail/logtail-ruby-rack#16]
I encountered an issue with my authentication system after integrating your service using the `http_header_filters` feature.

The problem arises when `collapse_into_single_event` is enabled (which is the default setting). In this scenario, the actual response headers are being filtered incorrectly by the `HTTPEvents` middleware. The specific line of code causing this issue can be found here:

https://github.com/logtail/logtail-ruby-rack/blob/909e7a235f53f4437b4240425436b0a3d769f713/lib/logtail-rack/http_events.rb#L152

**Comment by curusarn** [comment]
Hi @losadaem,

Thank you for raising this issue.

I'm passing this on to the team. I'll make sure to keep you updated here!


Thanks again for reaching out.

**Comment by PetrHeinz** [comment]
Hello @losadaem and thanks again for reporting the issue 🙌 

We've fixed the issue and released a new version of the gem https://github.com/logtail/logtail-ruby-rack/releases/tag/v0.2.5 Please upgrade to the patched version, and sorry for the problems with response headers. 🙏 

Feel free to reopen if you have any follow up questions. Always happy to help!
